#!/usr/bin/env bash
# Install a headless Chromium suitable for the visual bug check, with no
# system packages and no browser-CDN access required.
#
# How it works (learned the hard way):
#   - Playwright's own browser CDN is often blocked in sandboxes, but the npm
#     registry is not. The @sparticuz/chromium npm package SHIPS the browser
#     (brotli-compressed) inside its tarball, so we pull it from npm.
#   - The pack needs inflating (brotli) and its al2023/swiftshader/fonts tars
#     extracted; the GL libs must be symlinked next to the binary.
#   - Rendering form controls (<input>/<textarea>/<select>) crashes the build
#     unless fontconfig can see a real font set, so we assemble one:
#     system DejaVu (when available) + Noto Color Emoji (also from npm).
#
# Result: $BROWSER_DIR/env.sh, sourced by check.sh.
# Usage: install-browser.sh [--force]     (re-installs even if present)
set -euo pipefail

BROWSER_DIR="${BROWSER_DIR:-/tmp/win11web-browser}"
FORCE="${1:-}"

if [ "$FORCE" != "--force" ] && [ -x "$BROWSER_DIR/chromium" ] && [ -f "$BROWSER_DIR/env.sh" ]; then
  echo "==> browser already installed at $BROWSER_DIR (use --force to reinstall)"
  exit 0
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$BROWSER_DIR"

echo "==> fetching @sparticuz/chromium from npm registry"
npm pack @sparticuz/chromium --pack-destination "$WORK" >/dev/null 2>&1
tar xzf "$WORK"/sparticuz-chromium-*.tgz -C "$WORK" package/bin
cd "$WORK/package/bin"

echo "==> inflating brotli pack"
node -e '
const zlib = require("zlib"), fs = require("fs");
for (const f of ["chromium.br","al2023.tar.br","fonts.tar.br","swiftshader.tar.br"]) {
  fs.writeFileSync(f.replace(/\.br$/, ""), zlib.brotliDecompressSync(fs.readFileSync(f)));
}'

echo "==> extracting bundled libs / fonts / swiftshader"
mkdir -p lib fonts swiftshader
tar xf al2023.tar   -C lib
tar xf fonts.tar   -C fonts
tar xf swiftshader.tar -C swiftshader
# the build resolves its GLES lib relative to the binary
ln -sf swiftshader/libEGL.so  .
ln -sf swiftshader/libGLESv2.so .

echo "==> assembling font set (DejaVu + Noto Color Emoji)"
SYSFONTS="$BROWSER_DIR/sysfonts"
mkdir -p "$SYSFONTS" "$BROWSER_DIR/fontcache" "$BROWSER_DIR/fc"
if [ -d /usr/share/fonts/truetype/dejavu ]; then
  cp /usr/share/fonts/truetype/dejavu/*.ttf "$SYSFONTS/" 2>/dev/null || true
fi
if ! ls "$SYSFONTS" | grep -qi emoji; then
  npm pack noto-color-emoji --pack-destination "$WORK" >/dev/null 2>&1
  tar xzf "$WORK"/noto-color-emoji-*.tgz -C "$WORK" package/ttf/NotoColorEmoji.ttf
  cp "$WORK/package/ttf/NotoColorEmoji.ttf" "$SYSFONTS/"
fi
cat > "$BROWSER_DIR/fc/fonts.conf" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>$SYSFONTS</dir>
  <cachedir>$BROWSER_DIR/fontcache</cachedir>
  <config></config>
</fontconfig>
EOF

echo "==> installing to $BROWSER_DIR"
install -m 0755 chromium "$BROWSER_DIR/chromium"
# the al2023 tar nests a lib/ dir; flatten it next to the binary
mkdir -p "$BROWSER_DIR/lib"
if [ -d lib/lib ]; then cp -r lib/lib/. "$BROWSER_DIR/lib/"; else cp -r lib/. "$BROWSER_DIR/lib/"; fi
cp -r swiftshader/. "$BROWSER_DIR/swiftshader/"
# the build resolves its GLES/Vulkan libs relative to the binary
ln -sf swiftshader/libEGL.so  "$BROWSER_DIR/libEGL.so"
ln -sf swiftshader/libGLESv2.so "$BROWSER_DIR/libGLESv2.so"

cat > "$BROWSER_DIR/env.sh" <<EOF
# generated by visual-bugcheck/install-browser.sh
export CHROME_BIN="$BROWSER_DIR/chromium"
export FONTCONFIG_PATH="$BROWSER_DIR/fc"
export LD_LIBRARY_PATH="$BROWSER_DIR/lib"
EOF

echo "==> browser OK: $BROWSER_DIR/chromium"
